version: "3.9"

services:

  #
  # Sensors
  #

  sensor_spo2:
    build: ./sensors/spo2
    container_name: sensor_spo2
    env_file:
      - .env
    depends_on:
      - mosquitto

  sensor_hr:
    build: ./sensors/hr
    container_name: sensor_hr
    env_file:
      - .env
    depends_on:
      - mosquitto

  sensor_rr:
    build: ./sensors/rr
    container_name: sensor_rr
    env_file:
      - .env
    depends_on:
      - mosquitto

  sensor_bp:
    build: ./sensors/bp
    container_name: sensor_bp
    env_file:
      - .env
    depends_on:
      - mosquitto

  #
  # Broker
  #

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    env_file:
      - .env
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/passwd:/broker/passwd

  #
  # Monitor
  #

  monitor:
    build: ./monitor
    container_name: monitor
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      SOURCE: sim
    restart: unless-stopped

  #
  # Telegraf
  #

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  #
  # Knowledge
  #

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: acrss
      DOCKER_INFLUXDB_INIT_BUCKET: acrss
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: unless-stopped

  #
  # Analyzer
  #

  analyzer:
    build:
      context: .
      dockerfile: analyzer/Dockerfile
    container_name: analyzer
    depends_on:
      - mosquitto
      - influxdb
    env_file:
      - .env
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: analyzer-01
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      PATIENT_ID: 1
      SOURCE: sim
    restart: unless-stopped

  
  #
  # Planner
  #

  planner:
    build:
      context: .
      dockerfile: planner/Dockerfile
    container_name: planner
    depends_on:
      - mosquitto
      - influxdb
    env_file:
      - .env
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: planner-01
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      PATIENT_ID: 1
      SOURCE: sim
    restart: unless-stopped
  
  #
  # Executor
  #

  executor:
    build:
      context: .
      dockerfile: executor/Dockerfile
    container_name: executor
    env_file:
      - .env
    depends_on:
      - mosquitto
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}

      MQTT_HOSTNAME: ${MQTT_HOSTNAME}
      MQTT_PORT: ${MQTT_PORT}

      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      THERAPIES_TOPICS_PREFIX: ${THERAPIES_TOPICS_PREFIX}
      ACTIONS_TOPICS_PREFIX: ${ACTIONS_TOPICS_PREFIX}
      
      OXYGEN_ACTUATOR_NAME: ${OXYGEN_ACTUATOR_NAME}
      FLUIDS_ACTUATOR_NAME: ${FLUIDS_ACTUATOR_NAME}
      BETA_BLOCKING_ACTUATOR_NAME: ${BETA_BLOCKING_ACTUATOR_NAME}
      ALERT_ACTUATOR_NAME: ${ALERT_ACTUATOR_NAME}
    restart: unless-stopped

  #
  # Actuators
  #

  actuators:
    build:
      context: .
      dockerfile: actuators/Dockerfile
    container_name: actuators
    env_file:
      - .env
    depends_on:
      - mosquitto
    environment:
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}

      PATIENTS_NUMBER: ${PATIENTS_NUMBER}

      MQTT_HOSTNAME: ${MQTT_HOSTNAME}
      MQTT_PORT: ${MQTT_PORT}
      ACTIONS_TOPICS_PREFIX: ${ACTIONS_TOPICS_PREFIX}

      OXYGEN_ACTUATOR_NAME: ${OXYGEN_ACTUATOR_NAME}
      OXYGEN_FLOW_RATE_UNIT: ${OXYGEN_FLOW_RATE_UNIT}
      FLUIDS_ACTUATOR_NAME: ${FLUIDS_ACTUATOR_NAME}
      BETA_BLOCKING_ACTUATOR_NAME: ${BETA_BLOCKING_ACTUATOR_NAME}
      BETA_BLOCKING_FLOW_RATE_UNIT: ${BETA_BLOCKING_FLOW_RATE_UNIT}
      ALERT_ACTUATOR_NAME: ${ALERT_ACTUATOR_NAME}

  #
  # Dashboard
  #

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

  #
  # Node-red
  #
  node-red:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    container_name: node-red
    ports:
      - "1880:1880"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

    volumes:
      - ./nodered/data:/data


volumes:
  influxdb_data:
  influxdb_config:
  grafana_data:
