version: '3.9'

services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
      DOCKER_INFLUXDB_INIT_ORG: acrss
      DOCKER_INFLUXDB_INIT_BUCKET: acrss
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: acrss-super-token
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  sensor_spo2:
    build: ./sensors/spo2
    container_name: sensor_spo2
    depends_on:
      - mosquitto

  sensor_hr:
    build: ./sensors/hr
    container_name: sensor_hr
    depends_on:
      - mosquitto

  sensor_rr:
    build: ./sensors/rr
    container_name: sensor_rr
    depends_on:
       - mosquitto

  sensor_bp:
    build: ./sensors/bp
    container_name: sensor_bp
    depends_on:
      - mosquitto
  
  monitor:
    build: ./monitor
    container_name: monitor
    depends_on:
      - mosquitto
      - influxdb
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: acrss-super-token
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      PATIENT_ID: p1
      SOURCE: sim
    restart: unless-stopped


  analyzer:
    build: ./analyzer
    container_name: analyzer
    depends_on:
      - mosquitto
      - influxdb
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: analyzer-01
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: acrss-super-token
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      PATIENT_ID: p1
      SOURCE: sim
    restart: unless-stopped
  
  planner:
    build: ./planner
    container_name: planner
    depends_on:
      - mosquitto
      - influxdb
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: planner-01
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: acrss-super-token
      INFLUX_ORG: acrss
      INFLUX_BUCKET: acrss
      PATIENT_ID: p1
      SOURCE: sim
    restart: unless-stopped

volumes:
  influxdb_data:
  influxdb_config:

