version: "3.9"

services:
  #
  # Managed Resources
  #

  managed-resources:
    build:
      context: .
      dockerfile: managed_resources/Dockerfile
    container_name: managed-resources
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  #
  # Broker
  #

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    env_file:
      - .env
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/passwd:/broker/passwd

  #
  # Monitor
  #

  monitor:
    build: ./monitor
    container_name: monitor
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  #
  # Telegraf
  #

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  #
  # Knowledge
  #

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: acrss
      DOCKER_INFLUXDB_INIT_BUCKET: acrss
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    restart: unless-stopped

  #
  # Analyzer
  #

  analyzer:
    build:
      context: .
      dockerfile: analyzer/Dockerfile
    container_name: analyzer
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

  #
  # Planner
  #

  planner:
    build:
      context: .
      dockerfile: planner/Dockerfile
    container_name: planner
    env_file:
      - .env
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

  #
  # Executor
  #

  executor:
    build:
      context: .
      dockerfile: executor/Dockerfile
    container_name: executor
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  #
  # Dashboard
  #

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

  #
  # Node-red
  #
  node-red:
    build:
      context: ./nodered
      dockerfile: Dockerfile
    container_name: node-red
    ports:
      - "1880:1880"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

    volumes:
      - ./nodered/data:/data

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data: